POST http://localhost:3000/posts
Content-Type: application/json



{
  "title": "New Post Title",
  "postType": "post",
  "slug": "new-post-title",
  "status": "draft",
  "content": "This is the content of the new post.",
  "schema": "{\r\n \"@content\":\"https://schema.org\",\r\n \"@type\":\"Person\"\r\n}",
  "featuredImageUrl": "http://localhost.com/images/imageq.jpg",
  "publishOn": "2023-10-01T12:00:00Z",
  "tags": ["nestjs", "typescript"],
  "metaOptions": [
    {
      "key": "testKey",
      "value": 20
    }
  ]
}
